# Generated by Django 3.1.14 on 2021-12-13 11:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("base_app", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofilemodel",
            name="id",
        ),
        migrations.AlterField(
            model_name="userprofilemodel",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                serialize=False,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
