# Generated by Django 3.1.14 on 2021-12-18 01:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("records", "0003_kidmodel"),
    ]

    operations = [
        migrations.AlterField(
            model_name="familymodel",
            name="name",
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name="familymodel",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="kidmodel",
            name="family",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="records.familymodel"
            ),
        ),
    ]
