# Generated by Django 3.1.14 on 2021-12-21 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("records", "0004_auto_20211217_2022"),
    ]

    operations = [
        migrations.AddField(
            model_name="kidmodel",
            name="gender",
            field=models.CharField(
                choices=[("boy", "Boy"), ("girl", "Girl")], max_length=10, null=True
            ),
        ),
    ]
