# Generated by Django 3.1.14 on 2022-01-05 01:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("records", "0005_kidmodel_gender"),
    ]

    operations = [
        migrations.AlterField(
            model_name="familymodel",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
                unique=True,
            ),
        ),
    ]
